services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: db_uas
      DB_USERNAME: root
      DB_PASSWORD:

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: db_uas
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
